### ISSUE TITLE
linux compatibility error?

### ISSUE THREAD

**Issue by Swearinbag** [ExtraConcentratedJuice/pokecord-catcher#180]
I tried running this bot on linux (raspberrypi) and it worked without issue except when it found a pokemon I got this error:

Detected pokemon, catching...

System.TypeInitializationException: The type initializer for 'System.Drawing.GDIPlus' threw an exception. ---> System.DllNotFoundException: Unable to load DLL 'gdiplus': The specified module or one of its dependencies could not be found.
 (Exception from HRESULT: 0x8007007E)
   at System.Drawing.GDIPlus.GdiplusStartup(UInt64& token, GdiplusStartupInput& input, GdiplusStartupOutput& output)
   at System.Drawing.GDIPlus..cctor()
   --- End of inner exception stack trace ---
   at System.Drawing.GDIPlus.RunningOnUnix()
   at System.Drawing.Image.InitFromStream(Stream stream)
   at System.Drawing.Image.LoadFromStream(Stream stream, Boolean keepAlive)
   at PokecordCatcherBot.PokemonComparer.GetPokemon(Stream image) in E:\stuff\PokecordCatcher\PokecordCatcher\PokecordCatcher\PokemonComparer.cs:line 35
   at PokecordCatcherBot.Services.CatcherService.<OnMessage>d__3.MoveNext() in E:\stuff\PokecordCatcher\PokecordCatcher\PokecordCatcher\Services\CatcherService.cs:line 53
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at PokecordCatcherBot.Services.CatcherService.<>c__DisplayClass2_0.<<-ctor>b__2>d.MoveNext() in E:\stuff\PokecordCatcher\PokecordCatcher\PokecordCatcher\Services\CatcherService.cs:line 27

Is there a way that I can fix this? :)

**Comment by Swearinbag** [comment]
https://en.code-bude.net/2017/05/08/net-core-gdiplus-dll-not-found-in-linux/ <-- solution
