### ISSUE TITLE
not catching anything

### ISSUE THREAD

**Issue by memeersailor** [ExtraConcentratedJuice/pokecord-catcher#24]
i have the bot set up perfectly with configs edited fine, the bot isnt catching anything?

**Comment by memeersailor** [comment]
i also get this warning [Warning] Unknown Dispatch (SESSIONS_REPLACE)

**Comment by memeersailor** [comment]
sorry found a simlar issue

**Comment by ExtraConcentratedJuice** [comment]
did you somehow enable guild/pokemon whitelisting

**Comment by memeersailor** [comment]
neither are enabled, and if so they are set to the right guilds where i want them caught

**Comment by ExtraConcentratedJuice** [comment]
did you set the proper prefix for pokecord

**Comment by memeersailor** [comment]
yes, it is able to trade and display pokemon, but it doesnt catch any

**Comment by ExtraConcentratedJuice** [comment]
can you paste your config and a screenshot of the pokecord embed when the pokemon appears

**Comment by memeersailor** [comment]
![screen shot 2018-07-23 at 7 04 28 pm](https://user-images.githubusercontent.com/41558151/43112520-55376bf2-8eab-11e8-9b4c-33d42032e802.png)
![screen shot 2018-07-23 at 7 04 46 pm](https://user-images.githubusercontent.com/41558151/43112532-62aaf2ae-8eab-11e8-91d1-ed791d99c662.png)

**Comment by memeersailor** [comment]
Detected pokemon, catching...
this is all
ive had it running for a good day

**Comment by memeersailor** [comment]
i reinstalled a clean version from releases and redid everything, its still not catching anything, maybe i should use an older version?

**Comment by ExtraConcentratedJuice** [comment]
I've included stuff in the (latest release)[https://github.com/ExtraConcentratedJuice/pokecord-catcher/releases/tag/1.6.1] that will log any errors that the bot might've encountered during catching. Come back and paste the error that it logs here when you've tested it out

**Comment by memeersailor** [comment]
[Debug] Received Dispatch (MESSAGE_UPDATE)
System.TypeInitializationException: The type initializer for 'System.Drawing.GDIPlus' threw an exception. ---> System.DllNotFoundException: Unable to load shared library 'gdiplus' or one of its dependencies. In order to help diagnose loading problems, consider setting the DYLD_PRINT_LIBRARIES environment variable: dlopen(libgdiplus, 1): image not found
   at System.Drawing.GDIPlus.GdiplusStartup(UInt64& token, GdiplusStartupInput& input, GdiplusStartupOutput& output)
   at System.Drawing.GDIPlus..cctor()
   --- End of inner exception stack trace ---
   at System.Drawing.GDIPlus.RunningOnUnix()
   at System.Drawing.Image.InitFromStream(Stream stream)
   at System.Drawing.Image.LoadFromStream(Stream stream, Boolean keepAlive)
   at PokecordCatcherBot.PokemonComparer.GetPokemon(Stream image) in E:\stuff\PokecordCatcher\PokecordCatcher\PokecordCatcher\PokemonComparer.cs:line 36
   at PokecordCatcherBot.Services.CatcherService.OnMessage(SocketMessage msg) in E:\stuff\PokecordCatcher\PokecordCatcher\PokecordCatcher\Services\CatcherService.cs:line 48
   at PokecordCatcherBot.Services.CatcherService.<>c__DisplayClass2_0.<<-ctor>b__1>d.MoveNext() in E:\stuff\PokecordCatcher\PokecordCatcher\PokecordCatcher\Services\CatcherService.cs:line 25

this is the error when it tries to catch pokemon

**Comment by memeersailor** [comment]
seems im missing gdi plus, its probably cause im running this on a mac
ill try to find a fix and let you know so that this can support mac users

**Comment by ScriptKi77y** [comment]
didn't they change the images in some way? i believe they altered they so that hashing them produces a different hash from before. not sure though

**Comment by NoFiixx** [comment]
Also maybe role issues in the channel, maybe that's why the bot cant write anything...

**Comment by Peiffap** [comment]
Is there a way to get it to work on mac? I get the exact same issue you get...

**Comment by zRattly** [comment]
It gaves me the same error, i'm on an Ubuntu 18.04 VPS on the latest version on dotnet core.
