### ISSUE TITLE
Disconnected randomly

### ISSUE THREAD

**Issue by Idklife** [ExtraConcentratedJuice/pokecord-catcher#25]
[Warning]
[Info] Disconnecting

Unhandled Exception: [Info] Disconnected
System.Net.Http.HttpRequestException: No such host is known ---> System.Net.Sockets.SocketException: No such host is known
   at System.Net.Http.ConnectHelper.ConnectAsync(String host, Int32 port, CancellationToken cancellationToken)
   --- End of inner exception stack trace ---
   at System.Net.Http.ConnectHelper.ConnectAsync(String host, Int32 port, CancellationToken cancellationToken)
   at System.Threading.Tasks.ValueTask`1.get_Result()
   at System.Net.Http.HttpConnectionPool.CreateConnectionAsync(HttpRequestMessage request, CancellationToken cancellationToken)
   at System.Threading.Tasks.ValueTask`1.get_Result()
   at System.Net.Http.HttpConnectionPool.WaitForCreatedConnectionAsync(ValueTask`1 creationTask)
   at System.Threading.Tasks.ValueTask`1.get_Result()
   at System.Net.Http.HttpConnectionPool.SendWithRetryAsync(HttpRequestMessage request, Boolean doRequestAuth, CancellationToken cancellationToken)
   at System.Net.Http.RedirectHandler.SendAsync(HttpRequestMessage request, CancellationToken cancellationToken)
   at System.Net.Http.DecompressionHandler.SendAsync(HttpRequestMessage request, CancellationToken cancellationToken)
   at System.Net.Http.HttpClient.FinishSendAsyncBuffered(Task`1 sendTask, HttpRequestMessage request, CancellationTokenSource cts, Boolean disposeCts)
   at Discord.Net.Rest.DefaultRestClient.SendInternalAsync(HttpRequestMessage request, CancellationToken cancelToken, Boolean headerOnly)
   at Discord.Net.Rest.DefaultRestClient.SendAsync(String method, String endpoint, String json, CancellationToken cancelToken, Boolean headerOnly, String reason)
   at Discord.Net.Queue.JsonRestRequest.SendAsync()
   at Discord.Net.Queue.RequestBucket.SendAsync(RestRequest request)
   at Discord.Net.Queue.RequestQueue.SendAsync(RestRequest request)
   at Discord.API.DiscordRestApiClient.SendInternalAsync(String method, String endpoint, RestRequest request)
   at Discord.API.DiscordRestApiClient.SendJsonAsync[TResponse](String method, String endpoint, Object payload, String bucketId, ClientBucketType clientBucket, RequestOptions options)
   at Discord.API.DiscordRestApiClient.CreateMessageAsync(UInt64 channelId, CreateMessageParams args, RequestOptions options)
   at Discord.Rest.ChannelHelper.SendMessageAsync(IMessageChannel channel, BaseDiscordClient client, String text, Boolean isTTS, Embed embed, RequestOptions options)
   at Discord.WebSocket.SocketTextChannel.Discord.IMessageChannel.SendMessageAsync(String text, Boolean isTTS, Embed embed, RequestOptions options)
   at PokecordCatcherBot.Modules.SpammerService.DoSpam() in E:\stuff\PokecordCatcher\PokecordCatcher\PokecordCatcher\Modules\SpammerService.cs:line 31
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
--- End of stack trace from previous location where exception was thrown ---
   at System.Threading.ThreadPoolWorkQueue.Dispatch()
[Info] Connecting
~~
After it attempts to reconnect, the bot stops and I have to restart the bot manually.

**Comment by Idklife** [comment]
Oh right and another question about the trade pokemon feature.
The trade command still sends a trade offer to myself, how do I specify the bot to send a trade offer to my main account.
Example log;
**me**!trade celebi 
**Bot**: p!pokemon --name celebi
**Pokecord**: Your pokémon:
Celebi | Level: 1 | Number: 123 | IV: 50%
Celebi | Level: 1 | Number: 1234 | IV: 50%
**Bot**:p!trade (@)myself
Pokecord didn't create trade, aborting.

**Comment by ExtraConcentratedJuice** [comment]
Not entirely sure what would cause this, can you tell me more about your platform?

You can change the account that receives the trade by setting OwnerID in the configuration to the account's ID.
