### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by Grock123** [ExtraConcentratedJuice/pokecord-catcher#44]
Any idea what this error is and how to solve it?, I don't want to retype command run every 30 mins to get it started again.

Unhandled Exception: Discord.Net.HttpException: The server responded with error 500: 500: Internal Server Error
   at Discord.Net.Queue.RequestBucket.SendAsync(RestRequest request)
   at Discord.Net.Queue.RequestQueue.SendAsync(RestRequest request)
   at Discord.API.DiscordRestApiClient.SendInternalAsync(String method, String endpoint, RestRequest request)
   at Discord.API.DiscordRestApiClient.SendJsonAsync[TResponse](String method, String endpoint, Object payload, String bucketId, ClientBucketType clientBucket, RequestOptions options)
   at Discord.API.DiscordRestApiClient.CreateMessageAsync(UInt64 channelId, CreateMessageParams args, RequestOptions options)
   at Discord.Rest.ChannelHelper.SendMessageAsync(IMessageChannel channel, BaseDiscordClient client, String text, Boolean isTTS, Embed embed, RequestOptions options)
   at Discord.WebSocket.SocketTextChannel.Discord.IMessageChannel.SendMessageAsync(String text, Boolean isTTS, Embed embed, RequestOptions options)
   at PokecordCatcherBot.Services.SpammerService.DoSpam() in E:\stuff\PokecordCatcher\PokecordCatcher\PokecordCatcher\Services\SpammerService.cs:line 31
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
--- End of stack trace from previous location where exception was thrown ---
   at System.Threading.ThreadPoolWorkQueue.Dispatch()

**Comment by ExtraConcentratedJuice** [comment]
Seems like a lot of people are getting this error, but I can't replicate it. Can you tell me more about your platform?

**Comment by Grock123** [comment]
![screenshot_1](https://user-images.githubusercontent.com/41818408/43673075-150ba018-9782-11e8-8c13-7d8e6b38aadf.png)

64 bit
