### ISSUE TITLE
Error in CMD

### ISSUE THREAD

**Issue by bananas869** [ExtraConcentratedJuice/pokecord-catcher#49]
C:\Users\User\Desktop\publish>dotnet PokecordCatcher.dll
Loaded 806 pokemon
[Info] Discord.Net v2.0.0-beta (API v6)

Unhandled Exception: Discord.Net.HttpException: The server responded with error
401: 401: Unauthorized
   at Discord.Net.Queue.RequestBucket.SendAsync(RestRequest request)
   at Discord.Net.Queue.RequestQueue.SendAsync(RestRequest request)
   at Discord.API.DiscordRestApiClient.SendInternalAsync(String method, String e
ndpoint, RestRequest request)
   at Discord.API.DiscordRestApiClient.SendAsync[TResponse](String method, Strin
g endpoint, String bucketId, ClientBucketType clientBucket, RequestOptions optio
ns)
   at Discord.API.DiscordRestApiClient.GetVoiceRegionsAsync(RequestOptions optio
ns)
   at Discord.WebSocket.DiscordSocketClient.OnLoginAsync(TokenType tokenType, St
ring token)
   at Discord.Rest.BaseDiscordClient.LoginInternalAsync(TokenType tokenType, Str
ing token)
   at Discord.Rest.BaseDiscordClient.LoginInternalAsync(TokenType tokenType, Str
ing token)
   at Discord.Rest.BaseDiscordClient.LoginAsync(TokenType tokenType, String toke
n, Boolean validateToken)
   at PokecordCatcherBot.PokecordCatcher.Run() in E:\stuff\PokecordCatcher\Pokec
ordCatcher\PokecordCatcher\PokecordCatcher.cs:line 66
   at PokecordCatcherBot.Program.Main() in E:\stuff\PokecordCatcher\PokecordCatc
her\PokecordCatcher\Program.cs:line 11

Getting this error, any idea how I could fix it? 

.net Core Host also dies right after the error.

is the discord account we're using supposed to be used in browser, or desktop?

**Comment by bananas869** [comment]
Okay I figured it out, I was getting the token from the wrong place.

People that are getting this error are picking up "fingerprint" instead of the token.

For the actual token:

1. Go to discord on browser

2. CTRL + SHIFT + I and go to Networking, up top.

3. Send a DM to someone

4. Click on Messages

5. Click on Headers

6. look for "authorization"

7. Copy paste to config, that's your token.
