### ISSUE TITLE
Unauthorized- Config/Token Issues?

### ISSUE THREAD

**Issue by tokenluck** [ExtraConcentratedJuice/pokecord-catcher#52]
This basically follows after I put in the dotnet PokecordCatcher.dll into the command line:

Loaded 806 pokemon
[Info] Discord.Net v2.0.0-beta (API v6)

Unhandled Exception: Discord.Net.HttpException: The server responded with error 401: 401: Unauthorized
   at Discord.Net.Queue.RequestBucket.<SendAsync>d__18.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Discord.Net.Queue.RequestQueue.<SendAsync>d__14.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Discord.API.DiscordRestApiClient.<SendInternalAsync>d__62.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Discord.API.DiscordRestApiClient.<SendAsync>d__57`1.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Discord.API.DiscordRestApiClient.<GetVoiceRegionsAsync>d__142.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Discord.WebSocket.DiscordSocketClient.<OnLoginAsync>d__86.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Discord.Rest.BaseDiscordClient.<LoginInternalAsync>d__34.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at Discord.Rest.BaseDiscordClient.<LoginInternalAsync>d__34.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Discord.Rest.BaseDiscordClient.<LoginAsync>d__33.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at PokecordCatcherBot.PokecordCatcher.<Run>d__27.MoveNext() in E:\stuff\PokecordCatcher\PokecordCatcher\PokecordCatcher\PokecordCatcher.cs:line 66
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at PokecordCatcherBot.Program.Main() in E:\stuff\PokecordCatcher\PokecordCatcher\PokecordCatcher\Program.cs:line 11

I did check the similar issues (#49 specifically) and followed their instructions to obtain the proper token. Same error. I put the Owner ID by developer mode + right clicking my profile and copying the ID, same for the spam channel. My only thoughts is that its maybe I did the guilds wrong because I have absolutely no idea how they work. Thanks for reading?

**Comment by bananas869** [comment]
hey I made #49 . can u show settings with token and ID's blurred?

**Comment by ExtraConcentratedJuice** [comment]
yeah this is an issue with how you got the token, check to make sure it's right. guy above me linked to something that will help you get it
