### ISSUE TITLE
Error when running dotner pokecordCatcher.dll

### ISSUE THREAD

**Issue by rachelew10** [ExtraConcentratedJuice/pokecord-catcher#7]
An assembly specified in the application dependencies manifest (PokecordCatche
deps.json) was not found:
  package: 'CoreCompat.System.Drawing.v2', version: '5.2.0-preview1-r131'
  path: 'lib/netstandard2.0/CoreCompat.System.Drawing.dll'

**Comment by ExtraConcentratedJuice** [comment]
Are you using the release version found [here](https://github.com/ExtraConcentratedJuice/pokecord-catcher/releases)?

**Comment by rachelew10** [comment]
Thanks, just downloaded at it get's past the error I was having before. I'm using a bot token found under the app bot user in discord developer but now the following error comes up:

Unhandled Exception: Discord.Net.HttpException: The server responded with error
401: 401: Unauthorized
   at Discord.Net.Queue.RequestBucket.SendAsync(RestRequest request)
   at Discord.Net.Queue.RequestQueue.SendAsync(RestRequest request)
   at Discord.API.DiscordRestApiClient.SendInternalAsync(String method, String e
ndpoint, RestRequest request)
   at Discord.API.DiscordRestApiClient.SendAsync[TResponse](String method, Strin
g endpoint, String bucketId, ClientBucketType clientBucket, RequestOptions optio
ns)
   at Discord.API.DiscordRestApiClient.GetVoiceRegionsAsync(RequestOptions optio
ns)
   at Discord.WebSocket.DiscordSocketClient.OnLoginAsync(TokenType tokenType, St
ring token)
   at Discord.Rest.BaseDiscordClient.LoginInternalAsync(TokenType tokenType, Str
ing token)
   at Discord.Rest.BaseDiscordClient.LoginInternalAsync(TokenType tokenType, Str
ing token)
   at Discord.Rest.BaseDiscordClient.LoginAsync(TokenType tokenType, String toke
n, Boolean validateToken)
   at PokecordCatcherBot.PokecordCatcher.Run() in E:\stuff\PokecordCatcher\Pokec
ordCatcher\PokecordCatcher\PokecordCatcher.cs:line 168
   at PokecordCatcherBot.Program.Main() in E:\stuff\PokecordCatcher\PokecordCatc
her\PokecordCatcher\Program.cs:line 29


Do I need to use my discord account/ an alt account token?

**Comment by rachelew10** [comment]
Yes, thanks. Managed to get it working. Is there a way to delay the bot? For example 20s ish before catching the pokemon

**Comment by ExtraConcentratedJuice** [comment]
That functionality isn't implemented yet, I'll probably get to it some time in the future. You or somebody else can submit a pull request for it, though.
