### ISSUE TITLE
Failed to resume sessions

### ISSUE THREAD

**Issue by yeye26** [ExtraConcentratedJuice/pokecord-catcher#70]
The bot worked for some time but after like 2 hours without me interfering with it this happened and it doesn't work anymore.

> Loaded 806 pokemon
> [Info] Discord.Net v2.0.0-beta (API v6)
> [Info] Connecting
> [Warning] Unknown Dispatch (SESSIONS_REPLACE)
> [Info] Connected
> 
> Unhandled Exception: System.NullReferenceException: Object reference not set to an instance of an object.
>    at PokecordCatcherBot.Services.SpammerService.DoSpam() in E:\stuff\PokecordCatcher\PokecordCatcher\PokecordCatcher\Services\SpammerService.cs:line 30
>    at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
> --- End of stack trace from previous location where exception was thrown ---
>    at System.Threading.ThreadPoolWorkQueue.Dispatch()
> [Info] Ready
> [Warning] Failed to resume previous session

Thanks in advance.

**Comment by ExtraConcentratedJuice** [comment]
might just be an invalid spam channel
