### ISSUE TITLE
whitelisted pokemon error

### ISSUE THREAD

**Issue by CyncreVuar** [ExtraConcentratedJuice/pokecord-catcher#88]
Unhandled Exception: Newtonsoft.Json.JsonReaderException: After parsing a value an unexpected character was encountered: ". Path 'WhitelistedPokemon', line 10, position 1.
   at Newtonsoft.Json.JsonTextReader.ParsePostValue(Boolean ignoreComments)
   at Newtonsoft.Json.JsonTextReader.Read()
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.PopulateObject(Object newObject, JsonReader reader, JsonObjectContract contract, JsonProperty member, String id)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateObject(JsonReader reader, Type objectType, JsonContract contract, JsonProperty member, JsonContainerContract containerContract, JsonProperty containerMember, Object existingValue)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.Deserialize(JsonReader reader, Type objectType, Boolean checkAdditionalContent)
   at Newtonsoft.Json.JsonSerializer.DeserializeInternal(JsonReader reader, Type objectType)
   at Newtonsoft.Json.JsonConvert.DeserializeObject(String value, Type type, JsonSerializerSettings settings)
   at Newtonsoft.Json.JsonConvert.DeserializeObject[T](String value, JsonSerializerSettings settings)
   at PokecordCatcherBot.Util.ReadConfiguration[T](String path) in E:\stuff\PokecordCatcher\PokecordCatcher\PokecordCatcher\Util.cs:line 41
   at PokecordCatcherBot.PokecordCatcher.UpdateConfiguration(String fileName) in E:\stuff\PokecordCatcher\PokecordCatcher\PokecordCatcher\PokecordCatcher.cs:line 54
   at PokecordCatcherBot.PokecordCatcher..ctor() in E:\stuff\PokecordCatcher\PokecordCatcher\PokecordCatcher\PokecordCatcher.cs:line 25
   at PokecordCatcherBot.Program.Main() in E:\stuff\PokecordCatcher\PokecordCatcher\PokecordCatcher\Program.cs:line 11

This pops up and it has to do do something with the whitelist part but idk which part. help.

**Comment by ExtraConcentratedJuice** [comment]
``whitelisted: [guildid]`` not ``whitelisted: guildid``
