### ISSUE TITLE
401: 401: Unauthorized

### ISSUE THREAD

**Issue by OnlyRedx** [ExtraConcentratedJuice/pokecord-catcher#94]
Here is the exact message
`C:\Users\User\Desktop\Bot>dotnet PokecordCatcher.dll
Loaded 806 pokemon
[Info] Discord.Net v2.0.0-beta (API v6)

Unhandled Exception: Discord.Net.HttpException: The server responded with error 401: 401: Unauthorized
   at Discord.Net.Queue.RequestBucket.SendAsync(RestRequest request)
   at Discord.Net.Queue.RequestQueue.SendAsync(RestRequest request)
   at Discord.API.DiscordRestApiClient.SendInternalAsync(String method, String endpoint, RestRequest request)
   at Discord.API.DiscordRestApiClient.SendAsync[TResponse](String method, String endpoint, String bucketId, ClientBucketType clientBucket, RequestOptions options)
   at Discord.API.DiscordRestApiClient.GetVoiceRegionsAsync(RequestOptions options)
   at Discord.WebSocket.DiscordSocketClient.OnLoginAsync(TokenType tokenType, String token)
   at Discord.Rest.BaseDiscordClient.LoginInternalAsync(TokenType tokenType, String token)
   at Discord.Rest.BaseDiscordClient.LoginInternalAsync(TokenType tokenType, String token)
   at Discord.Rest.BaseDiscordClient.LoginAsync(TokenType tokenType, String token, Boolean validateToken)
   at PokecordCatcherBot.PokecordCatcher.Run() in E:\stuff\PokecordCatcher\PokecordCatcher\PokecordCatcher\PokecordCatcher.cs:line 66
   at PokecordCatcherBot.Program.Main() in E:\stuff\PokecordCatcher\PokecordCatcher\PokecordCatcher\Program.cs:line 11`

**Comment by OnlyRedx** [comment]
I figured out the issue.

Solution:
Did not use correct token ID.
